# -*- coding: utf-8 -*-
"""simple Password Generator using python for Cybersecurity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uvgr39zsjXNBdBeL9p6oNXDPCQOzTJUX
"""

from string import ascii_letters

for i in ascii_letters:
  for j in ascii_letters:
    for k in ascii_letters:
      for l in ascii_letters:
        print(i, j, k, l)